services:

  postgres-db:
    image: postgres:15
    container_name: postgres-db
    restart: always
    environment:
      POSTGRES_DB: billing-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data  

  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.4
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.4.4
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  gateway:
    build: ./gateway
    container_name: gateway
    ports:
      - "4001:4001"
    depends_on:
      - demo
      - auth-service
      - billing-service
      - bill-service

  demo:
    build: ./demo
    container_name: demo
    ports:
      - "4000:4000"
    depends_on:
      - postgres-db
      - kafka
    restart: always

  billing-service:
    build: ./billing-service
    container_name: billing-service
    ports:
      - "4002:4002"
    depends_on:
      - postgres-db
      - kafka
    restart: always

  bill-service:
    build: ./billservice
    container_name: billservice
    ports:
      - "4003:4003"
    depends_on:
      - postgres-db
      - kafka

  auth-service:
    build: ./authservice
    container_name: authservice
    ports:
      - "4005:4005"

  analytics-ai-service:
    build: ./analytics-ai-service
    container_name: analytics-ai-service
    ports:
      - "4006:4006"
    depends_on:
      - postgres-db

  notificationservice:
    build: ./notificationservice
    container_name: notificationservice
    ports:
      - "4008:4008"
    depends_on:
      - postgres-db

# ✅ MUST be at root level
volumes:
  postgres-data: