server:
  port: 4001

spring:
  cloud:
    gateway:
      globalcors:
        add-to-simple-url-handler-mapping: true
        corsConfigurations:
          '[/**]':
            allowedOrigins: "http://localhost:3039"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
            allowCredentials: true

      routes:
        - id: patient-service-route
          uri: http://demo:4000
          predicates:
            - Path=/api/patients/**
          filters:
            - AuthenticationFilter  

        - id: auth-service-route
          uri: http://auth-service:4005
          predicates:
            - Path=/api/auth/**

        - id: billing-service-route
          uri: http://billing-service:4002
          predicates:
            - Path=/api/billing/**
          filters:
            - AuthenticationFilter  

        - id: bill-service-route
          uri: http://billservice:4003
          predicates:
            - Path=/api/bill/**
          filters:
            - AuthenticationFilter  