spring.application.name=demo

spring.datasource.url=jdbc:postgresql://postgres-db:5432/billing-db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver
billing.service.billing-service=billing-service

server.port = 4000


spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.consumer.group-id=patient-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.properties.spring.json.trusted.packages=*
logging.file.name=logs/app.log
logging.level.root=INFO
logging.level.com.yourpackage=DEBUG

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=vasugoel4308@gmail.com
spring.mail.password=coxcqvredfjuqvkj

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true