spring.application.name=billing-service
server.port = 4002
# grpc.server.port = 9001

spring.datasource.url=jdbc:postgresql://postgres-db:5432/billing-db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update

spring.datasource.driver-class-name=org.postgresql.Driver

spring.kafka.bootstrap-servers=kafka:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=com.example.billing_service.Kafkaconsumer.PatientCreatedEventDeserializer

spring.kafka.consumer.group-id=patient-group
spring.kafka.consumer.auto-offset-reset=earliest