spring.application.name=authservice

server.port=4005
JWT_SECRET= Y2423432543534dfgrsgf25432tr3

spring.datasource.url=jdbc:postgresql://postgres-db:5432/patient_db
spring.datasource.username=postgres
spring.datasource.password=password
spring.jpa.hibernate.ddl-auto=update